### ISSUE TITLE
报错显示Process completed with exit code 1

### ISSUE THREAD

**Issue by Ramonddddddd** [xiazhongyv/PKUAutoSubmit_online#15]
Annotations
1 error

build
Process completed with exit code 1.

**Comment by zfthys** [comment]
我也有相同问题
![Update-main-yml-·-zfthys-PKUAutoSubmit_online-b500cca](https://user-images.githubusercontent.com/44822318/142797176-a150ee4f-28a4-491c-9cb9-d5482bd7a16e.png)

**Comment by James-Harden-13-R** [comment]
我也是，自动运行报错，手动运行一次好了

**Comment by manmadezz** [comment]
我今天也遇到这样的问题，而且手动运行也不太行？

**Comment by kaninnaliko** [comment]
之前偶尔自动运行失败，手动运行一次就好了。但今天手动运行好多次都不行，一直是报这个错

**Comment by xiazhongyv** [comment]
> 之前偶尔自动运行失败，手动运行一次就好了。但今天手动运行好多次都不行，一直是报这个错

这是因为github actions环境的chrome更新了。今天已经更新了，请重新pull或fork最新的代码。
重新克隆仓库或从上游更新代码后，请务必记得修改config.ini文件和.github/workflows/main.yml文件

**Comment by James-Harden-13-R** [comment]
我又报错了...


`Traceback (most recent call last):
  File "main.py", line 46, in <module>
    go('config.ini')
  File "main.py", line 25, in go
    habitation, district, street, capture, path, wechat, argconf.SENDKEY)
  File "/home/runner/work/PKUAutoSubmit_online/PKUAutoSubmit_online/func.py", line 298, in run
    fill_out(driver, campus, mail_address, phone_number, reason, detail, destination, track)
  File "/home/runner/work/PKUAutoSubmit_online/PKUAutoSubmit_online/func.py", line 198, in fill_out
    write_reason(driver, reason)
  File "/home/runner/work/PKUAutoSubmit_online/PKUAutoSubmit_online/func.py", line 106, in write_reason
    driver.find_element_by_xpath(f'//li/span[text()="{reason}"]').click()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 81, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 710, in _execute
    return self._parent.execute(command, params)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <span>...</span> is not clickable at point (80, 360). Other element would receive the click: <li data-v-28db1654="" class="el-select-dropdown__item">...</li>
  (Session info: headless chrome=96.0.4664.45)`

**Comment by James-Harden-13-R** [comment]
> 我又报错了...
> 
> `Traceback (most recent call last): File "main.py", line 46, in <module> go('config.ini') File "main.py", line 25, in go habitation, district, street, capture, path, wechat, argconf.SENDKEY) File "/home/runner/work/PKUAutoSubmit_online/PKUAutoSubmit_online/func.py", line 298, in run fill_out(driver, campus, mail_address, phone_number, reason, detail, destination, track) File "/home/runner/work/PKUAutoSubmit_online/PKUAutoSubmit_online/func.py", line 198, in fill_out write_reason(driver, reason) File "/home/runner/work/PKUAutoSubmit_online/PKUAutoSubmit_online/func.py", line 106, in write_reason driver.find_element_by_xpath(f'//li/span[text()="{reason}"]').click() File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 81, in click self._execute(Command.CLICK_ELEMENT) File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 710, in _execute return self._parent.execute(command, params) File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute self.error_handler.check_response(response) File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response raise exception_class(message, screen, stacktrace) selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <span>...</span> is not clickable at point (80, 360). Other element would receive the click: <li data-v-28db1654="" class="el-select-dropdown__item">...</li> (Session info: headless chrome=96.0.4664.45)`
手动运行第二次好了

**Comment by James-Harden-13-R** [comment]
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/urllib/request.py", line 1350, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/http/client.py", line 976, in send
    self.connect()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/http/client.py", line 1451, in connect
    server_hostname=server_hostname)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 46, in <module>
    go('config.ini')
  File "main.py", line 25, in go
    habitation, district, street, capture, path, wechat, argconf.SENDKEY)
  File "/home/runner/work/PKUAutoSubmit_online/PKUAutoSubmit_online/func.py", line 310, in run
    wechat_notification(userName, sckey)
  File "/home/runner/work/PKUAutoSubmit_online/PKUAutoSubmit_online/func.py", line 284, in wechat_notification
    safe='/:?=&')) as response:
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/urllib/request.py", line 1393, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/urllib/request.py", line 1352, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>
Error: Process completed with exit code 1.


这是报备成功了，但是微信推送没有成功？

**Comment by xiazhongyv** [comment]
> 今天也失败了，手动运行第二次好了~

可以更新下最新的版本，现在的新版本会重试，反复失败五次才会最终失败。
而且甚至改[这一行](https://github.com/xiazhongyv/PKUAutoSubmit_online/blob/master/main.py#L266)的数字，改成重试一百次一千次都行（雾）

**Comment by zhang20030917** [comment]
python3 main.py
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/[3](https://github.com/zhang20030917/-/actions/runs/3807008693/jobs/6476305919#step:6:3).11.0/x6[4](https://github.com/zhang20030917/-/actions/runs/3807008693/jobs/6476305919#step:6:4)
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.0/x64/lib
Traceback (most recent call last):
  File "/home/runner/work/-/-/main.py", line 22[5](https://github.com/zhang20030917/-/actions/runs/3807008693/jobs/6476305919#step:6:5), in <module>
    weather, temp, wind_dir,xigua = get_weather(region)
                                    ^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/-/-/main.py", line 45, in get_weather
    location_id = response['HeWeather[6](https://github.com/zhang20030917/-/actions/runs/3807008693/jobs/6476305919#step:6:6)'][0]["basic"]["cid"]
                  ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'basic'
{'HeWeather6': [{'status': 'permission denied'}]}
Error: Process completed with exit code 1.
这种咋解决？？

**Comment by wyxdlz54188** [comment]
https://github.com/wyxdlz54188/wyxdlz54188.github.io/actions/runs/13410974145
可以帮忙看下怎么回事吗，改了一个 liziblog.us.kg 的域名然后更新就报错
