### ISSUE TITLE
Process completed with exit code 1.

### ISSUE THREAD

**Issue by youngsteryuan** [xiazhongyv/PKUAutoSubmit_online#5]
大佬这是咋回事

Traceback (most recent call last):
  File "main.py", line 59, in <module>
    go('config.ini')
  File "main.py", line 38, in go
    habitation, district, street, capture, path, wechat, argconf.SENDKEY)
  File "/home/runner/work/PKUAutoSubmit_online/PKUAutoSubmit_online/func.py", line 294, in run
    wechat_notification(userName, sckey)
  File "/home/runner/work/PKUAutoSubmit_online/PKUAutoSubmit_online/func.py", line 268, in wechat_notification
    safe='/:?=&')) as response:
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
Error: Process completed with exit code 1.

**Comment by xiazhongyv** [comment]
已经更新啦，请重新Fork或者Fetch and merge upstream试一下~ 
更新之后不要忘记改config.ini以及workflow下的corn表达式哦
